spring:
  profiles:
    active: dev
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/dbspringboot
    username: xlzhang
    password: xlzhang
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true